appname: "Perlresume"

layout: "main"

charset: "UTF-8"

template: "caml"

plugins:
    Database:
        connections:
            perlresume:
                driver: 'SQLite'
                database: 'perlresume.db'
            cpants:
                driver: 'SQLite'
                database: 'cpants_all.db'
